from __future__ import annotations

import html

from ...core.auth.activation_manager import (
    build_utm_url,
    get_dashboard_url,
    get_server_config,
)
from ...core.errors import NETWORK_ERROR_CODES
from ...core.i18n import tr

DASHBOARD_ERROR_URL = build_utm_url("/dashboard", "dashboard_error")
SUBSCRIBE_ERROR_URL = build_utm_url("/dashboard/ai-edit", "subscribe")


def _localize_server_error(error: str, code: str) -> str:
    """Replace an English server error string with its localized equivalent
    when the server's `code` is one we know about. Keeps the original English
    text for unknown codes so users still see something actionable.

    The server stays i18n-agnostic: it sends stable codes; the plugin owns the
    user-facing copy. Adding a new server error code = add one branch here and
    one tr() string in the .ts files.

    Unknown/empty codes fall back to the raw server string html-escaped: the
    status label is AutoText, so unescaped markup would render.
    """
    if not code:
        return html.escape(error or "")
    mapping = {
        # Connectivity codes (client-generated by terralab_client). The base
        # sentence stays short here; _enrich_error_message appends the matching
        # actionable hint so the two never duplicate "check your connection".
        "NO_NETWORK": tr("No internet connection."),
        "DNS_ERROR": tr("Cannot reach the server."),
        "TIMEOUT": tr("The request timed out."),
        "SSL_ERROR": tr("Secure connection failed."),
        "PROXY_ERROR": tr("Proxy connection failed."),
        "CONNECTION_REFUSED": tr("Could not connect to the service."),
        "AUTH_ERROR": tr("Authentication failed. Check your activation key."),
        # Account / key codes (server-generated). Translated here so a French
        # user never sees the raw English server string.
        "NO_KEY": tr("No activation key. Enter your key to use AI Edit."),
        "INVALID_KEY": tr("Invalid activation key."),
        "KEY_REVOKED": tr("This activation key has been revoked."),
        "SUBSCRIPTION_EXPIRED": tr("Your subscription has expired."),
        "SUBSCRIPTION_INACTIVE": tr("Your subscription is inactive."),
        "FREE_TIER_EXPIRED": tr("Your free trial has ended."),
        "DEVICE_LIMIT_EXCEEDED": tr(
            "This license is already in use on the maximum number of computers."
            " Free one in your account, or wait for an inactive one to expire."
        ),
        "RATE_LIMITED": tr("Too many requests, please wait a moment."),
        "RATE_LIMITER_DOWN": tr("Service temporarily unavailable, please retry shortly."),
        "STORAGE_UNAVAILABLE": tr("Storage temporarily unavailable, please retry shortly."),
        "SIGN_FAILED": tr("Could not prepare upload, please retry shortly."),
        "UPLOAD_TOKEN_INVALID": tr("Upload session expired, please retry."),
        "UPLOAD_TOKEN_MISMATCH": tr("Upload session does not match your account."),
        "WRONG_PRODUCT": tr("This activation key is for a different product."),
        "WRONG_REQUEST": tr("Unknown or unauthorized request."),
        "AUTH_MIGRATION_REQUIRED": tr("Account migration required, please re-login from the website."),
        "NOT_READY": tr("Result not ready yet."),
        "NOT_AVAILABLE": tr("Result not available."),
        "UPSTREAM_UNAVAILABLE": tr("Result temporarily unavailable, please retry shortly."),
        "UPSTREAM_EMPTY": tr("Result temporarily unavailable, please retry shortly."),
        "PROVIDER_BAD_RESPONSE": tr("The generation service returned an unexpected response, please retry."),
        "PROVIDER_ERROR": tr("Generation failed, please try again."),
        "MISCONFIGURED": tr("Service not configured. Please contact support."),
        "SERVER_ERROR": tr("Service temporarily unavailable, please retry shortly."),
        "DB_ERROR": tr("Database error, please retry shortly."),
        "BAD_REQUEST": tr("Invalid request. Check your prompt and the selected area, then try again."),
        "BAD_INPUT": tr("Invalid input. Check your prompt and the selected area."),
        "INVALID_INPUT": tr("Invalid input. Try a different image or selection."),
        "PAYLOAD_TOO_LARGE": tr("Image too large. Try selecting a smaller area or lowering the resolution."),
        "RESOLUTION_NOT_ALLOWED": tr(
            "This detail level is not available on your plan."
            " Upgrade to unlock more detail."
        ),
        "NOT_FOUND": tr("Resource not found."),
        "NOT_SEEDED": tr("Catalog not yet available, please retry shortly."),
        "DEMO_FETCH_FAILED": tr("Could not load the demo preview."),
        "UNKNOWN_TEMPLATE": tr("Unknown template."),
    }
    localized = mapping.get(code)
    if localized is not None:
        return localized
    return html.escape(error or "")


# Three-tier failure-report policy, decided by error code:
#
#  Tier 1 (_USER_FIXABLE_CODES)  -> plain inline message, no log prompt.
#     The user owns the fix (their link, key, zone, plan). Not our bug.
#  Tier 2 (_TRANSIENT_CODES)     -> inline message + an optional "Report a
#     problem" link. Retryable and not clearly a fault (rate limit, a stale
#     upload session, a result not ready yet); the user can send a log if it
#     persists, but we never force a modal.
#  Tier 3 (everything else)       -> auto-open the log-report dialog. A network
#     timeout or a server-side fault is terminal for that generation either
#     way, so we want to hear about it right away rather than only see it as a
#     dip in completion telemetry (same tier the download/write/empty-response
#     and truly unknown codes already used).
_USER_FIXABLE_CODES = frozenset({
    "AUTH_ERROR",
    "NO_KEY", "INVALID_KEY", "KEY_REVOKED", "AUTH_LOCKED",
    "INVALID_CRS", "ANTIMERIDIAN", "POLAR", "TOO_LARGE",
    "MAP_ROTATED", "ZONE_TOO_SMALL", "PAYLOAD_TOO_LARGE",
    "BAD_REQUEST", "BAD_INPUT", "INVALID_INPUT", "RESOLUTION_NOT_ALLOWED",
    "QUOTA_EXCEEDED", "LIMIT_REACHED", "USAGE_LIMIT_REACHED",
    "MONTHLY_LIMIT_REACHED", "TRIAL_EXHAUSTED",
    "SUBSCRIPTION_EXPIRED", "SUBSCRIPTION_INACTIVE", "FREE_TIER_EXPIRED",
    "DEVICE_LIMIT_EXCEEDED",
    "GENERATION_CANCELLED",
})

# Pure-connectivity codes: the request never reached us at all because of
# something in the USER's own network path (no link, DNS, a corporate proxy,
# SSL inspection). Still not our bug, but not silent either: an optional
# report link lets someone who cannot self-diagnose their network send us a
# log. TIMEOUT is deliberately excluded: unlike these, it does not point at
# the user's own setup (it is just as often our server being slow or
# overloaded), so it is treated as a server-fault code below instead.
_CONNECTIVITY_CODES = NETWORK_ERROR_CODES - frozenset({"TIMEOUT"})

_TRANSIENT_CODES = _CONNECTIVITY_CODES | frozenset({
    "RATE_LIMITED", "NOT_READY", "NOT_AVAILABLE",
    "UPLOAD_TOKEN_INVALID", "UPLOAD_TOKEN_MISMATCH",
})

# Server-fault codes: our own infrastructure, or the upstream model provider,
# failed to answer at all (not merely busy or throttling). Not in either set
# above, so _report_policy's default already routes these to "dialog"; kept
# as an explicit set purely to document the classification.
_SERVER_FAULT_CODES = frozenset({
    "TIMEOUT", "GENERATION_TIMED_OUT",
    "SERVER_ERROR", "RATE_LIMITER_DOWN", "STORAGE_UNAVAILABLE", "SIGN_FAILED",
    "UPSTREAM_UNAVAILABLE", "UPSTREAM_EMPTY", "PROVIDER_ERROR", "PROVIDER_BAD_RESPONSE",
})

# Failures where a credit is never kept: the generation either never reached the
# charge point, or the server auto-refunds the failed job. We append a short
# "Aucun crédit utilisé." so the user is reassured on EVERY such error. The
# messages that already spell out the refund (download/write/timeout) and the
# model-failure branch carry their own wording and are intentionally excluded.
_CREDIT_REASSURE_CODES = frozenset({
    "GENERATION_FAILED", "SERVER_ERROR", "PROVIDER_ERROR", "PROVIDER_BAD_RESPONSE",
    "UPSTREAM_UNAVAILABLE", "UPSTREAM_EMPTY", "EMPTY_RESPONSE",
    "IMAGE_FORMAT_UNSUPPORTED", "STORAGE_UNAVAILABLE", "RATE_LIMITED",
    "RATE_LIMITER_DOWN", "MISCONFIGURED", "DB_ERROR", "NOT_AVAILABLE",
    "NOT_READY",
})


def _report_policy(normalized_code: str) -> str:
    """Return 'none' | 'link' | 'dialog' for a failure code (see tier comment)."""
    if normalized_code in _USER_FIXABLE_CODES:
        return "none"
    if normalized_code in _TRANSIENT_CODES:
        return "link"
    return "dialog"


def _enrich_error_message(error: str, code: str = "") -> str:
    """Translate the server-supplied error (via code), then append actionable
    guidance (deep links, network hints) based on the same code."""
    localized = _localize_server_error(error, code)
    if code in (
        "INVALID_KEY", "KEY_REVOKED",
        "SUBSCRIPTION_EXPIRED", "SUBSCRIPTION_INACTIVE", "FREE_TIER_EXPIRED",
    ):
        return f'{localized}. <a href="{DASHBOARD_ERROR_URL}">{tr("Check your dashboard")}</a>'
    if code == "TRIAL_EXHAUSTED":
        config = get_server_config()
        dashboard = config.get("upgrade_url", get_dashboard_url())
        return f'{localized}. <a href="{dashboard}">{tr("Subscribe")}</a>'
    if code == "DEVICE_LIMIT_EXCEEDED":
        return f'{localized} <a href="{DASHBOARD_ERROR_URL}">{tr("Manage your computers")}</a>'
    if code == "PROXY_ERROR":
        return f"{localized}. {tr('Check QGIS proxy settings: Settings > Options > Network')}"
    if code == "SSL_ERROR":
        return f"{localized}. {tr('If you are on a corporate network, ask your IT team about SSL inspection settings')}"
    if code in ("DNS_ERROR", "NO_NETWORK"):
        return f"{localized}. {tr('Check your internet connection')}"
    if code == "TIMEOUT":
        return f"{localized}. {tr('Try again, or check your internet speed')}"
    if code == "CONNECTION_REFUSED":
        return f"{localized}. {tr('The service may be temporarily unavailable')}"
    if code == "AUTH_ERROR":
        return f'{localized}. <a href="{DASHBOARD_ERROR_URL}">{tr("Check your dashboard")}</a>'
    return localized


# Substrings that mark a generation that the model couldn't produce (no image,
# safety block, server catch-all "couldn't complete"). The server marks these
# jobs failed and auto-refunds the credit, so they are a user-facing outcome,
# not a bug. Matched on the message because the failed-status response carries
# no specific error code (status route returns {status, error} only).
_MODEL_FAILURE_HINTS = (
    "no image",
    "no_image",
    "finish_reason",
    "no candidates",
    "block",
    "safety",
    "couldn't complete",
    "could not complete",
    "rephrasing your prompt",
    "no credit was charged",
)

_NON_MODEL_FAILURE_CODES = NETWORK_ERROR_CODES | frozenset({
    "QUOTA_EXCEEDED",
    "LIMIT_REACHED",
    "USAGE_LIMIT_REACHED",
    "MONTHLY_LIMIT_REACHED",
    "TRIAL_EXHAUSTED",
    "NO_KEY",
    "INVALID_KEY",
    "KEY_REVOKED",
    "AUTH_LOCKED",
    "SUBSCRIPTION_EXPIRED",
    "SUBSCRIPTION_INACTIVE",
    "FREE_TIER_EXPIRED",
    "AUTH_ERROR",
    "GENERATION_CANCELLED",
})


def _is_model_failure(message: str, normalized_code: str) -> bool:
    """True when the model couldn't produce an image (no-output / safety block /
    server catch-all). Network / auth / quota / cancel codes are excluded so
    only genuine generation failures (which the server auto-refunds) match."""
    if normalized_code in _NON_MODEL_FAILURE_CODES:
        return False
    text = (message or "").lower()
    return any(needle in text for needle in _MODEL_FAILURE_HINTS)


# Transient capacity errors: the image service is momentarily overloaded. The
# user was not charged (the server refunds), so show a calm "try again" message
# inline rather than the bug-report dialog.
_BUSY_HINTS = (
    "resource exhausted",
    "resource_exhausted",
    "too many requests",
    "rate limit",
    "rate-limit",
    "service is busy",
    "busy right now",
    "try again in a moment",
)


def _is_service_busy(message: str, normalized_code: str) -> bool:
    if normalized_code in {"RATE_LIMITED", "RESOURCE_EXHAUSTED", "PROVIDER_BUSY", "SERVICE_BUSY"}:
        return True
    text = (message or "").lower()
    return any(needle in text for needle in _BUSY_HINTS)


def _scrub_paths(text: str) -> str:
    """Strip usernames from any /Users/<name>, \\Users\\<name>, or /home/<name> path."""
    import re
    return re.sub(r"(?i)([/\\](?:Users|home)[/\\])[^/\\]+", r"\1***", text or "")


def _failure_stage(normalized_code: str) -> str:
    """Map an error code to the pipeline stage it failed at."""
    if normalized_code == "DOWNLOAD_FAILED":
        return "download"
    if normalized_code == "WRITE_ERROR":
        return "write"
    if normalized_code in {
        "NO_NETWORK", "DNS_ERROR", "SSL_ERROR", "TIMEOUT", "PROXY_ERROR",
        "CONNECTION_REFUSED", "TOO_LARGE", "BAD_REQUEST",
    }:
        return "submit"
    return "poll"


def _resolve_class_label(
    vector_color: str | None, vector_classes: list[dict] | None
) -> str:
    """Look up the semantic class name for ``vector_color`` in the multi-class
    catalog. Empty string when the template only declares a color, leaving
    the field blank in the table for the user to fill in (autocomplete kicks
    in after the first value is typed).
    """
    if not vector_color or not isinstance(vector_classes, list):
        return ""
    target = vector_color.upper().lstrip("#")
    for entry in vector_classes:
        if not isinstance(entry, dict):
            continue
        color = (entry.get("color") or "").upper().lstrip("#")
        if color and color == target:
            label = entry.get("label")
            if isinstance(label, str):
                return label.strip()
    return ""
