# Thin facade over the src/ui/dock/ package. Kept so every existing
# import path (plugin.py, dialogs) keeps working unchanged.
from .dock.mime import (  # noqa: F401
    _GEODATA_DROP_EXTS,
    _IMAGE_DROP_EXTS,
    _LAYERTREE_MIME,
    _URI_MIME,
    _file_paths_from_mime,
    _layers_from_mime,
    _mime_has_droppable,
)
from .dock.prompt_container import _PromptContainer  # noqa: F401
from .dock.style import (  # noqa: F401
    _BTN_BLUE,
    _BTN_BLUE_AUTH,
    _BTN_DISABLED,
    _BTN_GHOST,
    _BTN_GRAY,
    _BTN_GREEN,
    _BTN_GREEN_AUTH,
    _BTN_PAIR_CANCEL,
    _BTN_PAIR_NEUTRAL,
    _CHIP_HEIGHT,
    _FOOTER_ICON_BTN_STYLE,
    _FOOTER_ICON_TOGGLE_STYLE,
    _FOOTER_MENU_STYLE,
    _INSTRUCTION_BOX,
    BRAND_BLUE,
    BRAND_BLUE_HOVER,
    BRAND_DISABLED,
    BRAND_GRAY,
    BRAND_GRAY_HOVER,
    BRAND_GREEN,
    BRAND_GREEN_TEXT,
    BRAND_RED,
    BRAND_RED_HOVER,
    BTN_GREEN,
    BTN_GREEN_DISABLED,
    BTN_GREEN_HOVER,
    DISABLED_TEXT,
    ERROR_TEXT,
    MAX_PROMPT_CHARS,
    SUCCESS_TEXT,
    TERRALAB_URL,
    _pencil_icon,
    _picture_plus_icon,
    _tinted_svg_icon,
)
from .dock.widget import AIEditDockWidget, _make_section_header  # noqa: F401
from .dock.widgets import (  # noqa: F401
    _FooterIconButton,
    _PromptHighlighter,
    _ResolutionMenuItem,
    _Spinner,
    _SubmitTextEdit,
    _ZoneGestureGlyph,
)
