from __future__ import annotations

import os
import re
import time

from osgeo import gdal, osr
from qgis.core import QgsProject, QgsRasterLayer

from ..core.logger import log_debug, log_warning

# All rasters generated by the plugin land under this single, never-numbered
# layer-tree group so the user can tell at a glance which outputs come from
# AI Edit. Created lazily on the first generation of the session.
_AI_EDIT_GROUP_NAME = "AI-Edit"

# Formats GDAL reliably decodes across all platforms (esp. Windows OSGeo4W,
# which often ships without WebP/AVIF drivers).
_GDAL_SAFE_FORMATS = {"PNG", "JPEG", "TIFF", "GIF", "BMP"}


def _detect_image_format(data: bytes) -> str | None:
    """Identify the image format from magic bytes. Returns None if unknown."""
    if len(data) < 12:
        return None
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return "PNG"
    if data[:3] == b"\xff\xd8\xff":
        return "JPEG"
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "WebP"
    if data[:6] in (b"GIF87a", b"GIF89a"):
        return "GIF"
    if data[:2] in (b"II", b"MM") and data[2:4] in (b"\x2a\x00", b"\x00\x2a"):
        return "TIFF"
    if data[:2] == b"BM":
        return "BMP"
    # AVIF/HEIF: ftyp box at offset 4
    if len(data) >= 12 and data[4:8] == b"ftyp":
        brand = data[8:12]
        if brand in (b"avif", b"avis"):
            return "AVIF"
        if brand in (b"heic", b"heix", b"mif1", b"msf1"):
            return "HEIF"
    return None


def write_geotiff(
    image_data: bytes,
    extent_dict: dict,
    crs_wkt: str,
    output_dir: str,
    prompt: str = "",
    ctx=None,
) -> str:
    """Write raw image bytes as a georeferenced GeoTIFF.

    Uses only GDAL (no QgsRectangle or QgsCoordinateReferenceSystem)
    so it can safely run on a worker thread.

    Args:
        image_data: Raw image bytes (already downloaded from model)
        extent_dict: Dict with xmin, ymin, xmax, ymax in map coordinates
        crs_wkt: CRS as WKT string
        output_dir: Directory to save the GeoTIFF
        prompt: Original prompt (used in filename)

    Returns:
        Path to the created GeoTIFF file
    """
    os.makedirs(output_dir, exist_ok=True)

    timestamp = int(time.time())
    slug = _slugify(prompt)[:40] if prompt else "generated"
    filename = f"{timestamp}_{slug}.tif"
    output_path = os.path.join(output_dir, filename)

    xmin = extent_dict["xmin"]
    ymin = extent_dict["ymin"]
    xmax = extent_dict["xmax"]
    ymax = extent_dict["ymax"]

    if not image_data:
        raise RuntimeError("Server returned an empty response (0 bytes)")

    img_format = _detect_image_format(image_data)
    head_hex = bytes(image_data[:16]).hex()
    log_debug(
        f"GeoTIFF input: {len(image_data)} bytes, "
        f"format={img_format or 'unknown'}, head={head_hex}"
    )
    if img_format is None:
        log_warning(
            f"Unrecognized image payload ({len(image_data)} bytes, head={head_hex})"
        )
        raise RuntimeError(
            "Server returned data that is not a recognized image format. "
            "This usually means the server replied with an error page. "
            "Please try again or check the QGIS log."
        )

    # Use GDAL's in-memory VFS to avoid writing a temp file to disk.
    # On Windows, writing then deleting a temp file causes WinError 32 because
    # the GDAL PNG driver keeps the file handle open until GC runs.
    vsimem_path = f"/vsimem/_temp_{timestamp}.png"
    try:
        gdal.FileFromMemBuffer(vsimem_path, bytes(image_data))
        try:
            src_ds = gdal.Open(vsimem_path)
        except RuntimeError as e:
            if img_format not in _GDAL_SAFE_FORMATS:
                raise RuntimeError(
                    f"Image format {img_format} is not supported by your QGIS "
                    f"GDAL build. Please update QGIS or contact support."
                ) from e
            raise
        if src_ds is None:
            if img_format not in _GDAL_SAFE_FORMATS:
                raise RuntimeError(
                    f"Image format {img_format} is not supported by your QGIS "
                    f"GDAL build. Please update QGIS or contact support."
                )
            raise RuntimeError(
                f"Failed to open downloaded {img_format} image with GDAL"
            )

        recv_w = src_ds.RasterXSize
        recv_h = src_ds.RasterYSize
        src_bands = src_ds.RasterCount
        bands = min(src_bands, 3)
        log_debug(f"GeoTIFF: received {recv_w}x{recv_h}px, {bands} bands")

        ext_width = xmax - xmin
        ext_height = ymax - ymin
        log_debug(f"GeoTIFF extent: {ext_width:.2f}x{ext_height:.2f} map units")

        if ctx is not None:
            ctx.received_image_width = recv_w
            ctx.received_image_height = recv_h
            ctx.received_size_bytes = len(image_data)
            ctx.crop_offsets = (0, 0, recv_w, recv_h)

        # Keep full received resolution
        driver = gdal.GetDriverByName("GTiff")
        dst_ds = driver.Create(
            output_path, recv_w, recv_h, bands, gdal.GDT_Byte
        )
        if dst_ds is None:
            raise RuntimeError(f"Failed to create GeoTIFF at {output_path}")

        # Geotransform: map the received image pixels to the geographic extent.
        x_res = ext_width / recv_w
        y_res = ext_height / recv_h
        geotransform = (xmin, x_res, 0, ymax, 0, -y_res)
        dst_ds.SetGeoTransform(geotransform)

        if ctx is not None:
            ctx.output_path = output_path
            ctx.geotransform = geotransform
            ctx.output_bands = bands
            ctx.output_dimensions = (recv_w, recv_h)

        srs = osr.SpatialReference()
        srs.ImportFromWkt(crs_wkt)
        dst_ds.SetProjection(srs.ExportToWkt())

        dst_ds.SetMetadataItem("AI_EDIT_PROMPT", prompt)
        dst_ds.SetMetadataItem(
            "AI_EDIT_TIMESTAMP",
            time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        )
        dst_ds.SetMetadataItem("AI_EDIT_CRS", crs_wkt[:200])
        dst_ds.SetMetadataItem(
            "AI_EDIT_EXTENT",
            f"{xmin:.6f},{ymin:.6f},{xmax:.6f},{ymax:.6f}",
        )
        dst_ds.SetMetadataItem(
            "AI_EDIT_RESOLUTION",
            ctx.submitted_resolution if ctx else "unknown",
        )
        dst_ds.SetMetadataItem("AI_EDIT_MODEL", "AI Edit")

        for i in range(1, bands + 1):
            band_data = src_ds.GetRasterBand(i).ReadAsArray()
            dst_ds.GetRasterBand(i).WriteArray(band_data)

        dst_ds.FlushCache()
        dst_ds = None
        src_ds = None
    finally:
        gdal.Unlink(vsimem_path)

    return output_path


def add_geotiff_to_project(
    geotiff_path: str,
    prompt: str = "",
    generation_number: int | None = None,
) -> QgsRasterLayer:
    """Add GeoTIFF as a raster layer under the fixed 'AI-Edit' group."""
    if prompt:
        # Cap the layer name slug at ~25 chars (about half the old 55)
        # so the legend stays scannable. Trim on an underscore boundary
        # when possible so we don't cut mid-word.
        slug = _slugify(prompt)[:25] or "ai_edit_result"
        if len(prompt) > 25 and "_" in slug[:25]:
            slug = slug.rsplit("_", 1)[0]
    else:
        slug = "ai_edit_result"

    if generation_number is not None:
        display_name = f"#{generation_number} {slug}"
    else:
        display_name = slug

    existing_names = [lyr.name() for lyr in QgsProject.instance().mapLayers().values()]
    if display_name in existing_names:
        counter = 2
        while f"{display_name}_{counter}" in existing_names:
            counter += 1
        display_name = f"{display_name}_{counter}"

    layer = QgsRasterLayer(geotiff_path, display_name)
    if not layer.isValid():
        raise RuntimeError(f"Failed to create valid raster layer from {geotiff_path}")

    QgsProject.instance().addMapLayer(layer, False)
    root = QgsProject.instance().layerTreeRoot()
    group = root.findGroup(_AI_EDIT_GROUP_NAME)
    if group is None:
        group = root.insertGroup(0, _AI_EDIT_GROUP_NAME)
    node = group.insertLayer(0, layer)
    if node is not None:
        node.setExpanded(False)

    return layer


def get_output_dir() -> str:
    """Get the output directory for generated images."""
    from qgis.core import QgsApplication, QgsProject

    project = QgsProject.instance()
    project_path = project.absoluteFilePath()
    if project_path:
        return os.path.join(os.path.dirname(project_path), "ai_edit_outputs")
    return os.path.join(QgsApplication.qgisSettingsDirPath(), "ai_edit", "generated")


def _slugify(text: str) -> str:
    """Convert text to a filesystem-safe slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[-\s]+", "_", text)
    return text.strip("_")
