





from __future__ import annotations

import os
import struct

from .logger import log_warning
from .output_paths import (
    ascii_safe_dir,
    fallback_output_dir,
    remove_with_retry,
)
from .output_paths import unique_output_path as _unique_output_path






AI_DISCLAIMER_TEXT = "Synthetic imagery generated by AI. Not survey data or ground truth."

_FALLBACK_EXT = {
    "PNG": "png",
    "JPEG": "jpg",
    "GIF": "gif",
    "BMP": "bmp",
    "TIFF": "tif",
    "WebP": "webp",
    "AVIF": "avif",
    "HEIF": "heif",
}


def detect_image_format(data: bytes) -> str | None:

    if len(data) < 12:
        return None
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return "PNG"
    if data[:3] == b"\xff\xd8\xff":
        return "JPEG"
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "WebP"
    if data[:6] in (b"GIF87a", b"GIF89a"):
        return "GIF"
    if data[:4] in (b"II\x2a\x00", b"MM\x00\x2a", b"II\x2b\x00", b"MM\x00\x2b"):
        return "TIFF"
    if data[:2] == b"BM":
        return "BMP"

    if len(data) >= 12 and data[4:8] == b"ftyp":
        brand = data[8:12]
        if brand in (b"avif", b"avis"):
            return "AVIF"
        if brand in (b"heic", b"heix", b"mif1", b"msf1"):
            return "HEIF"
    return None


def read_image_dimensions(data: bytes, fmt: str | None) -> tuple[int, int]:


    try:
        if fmt == "PNG" and len(data) >= 24 and data[12:16] == b"IHDR":
            w, h = struct.unpack(">II", data[16:24])
            return int(w), int(h)
        if fmt == "GIF" and len(data) >= 10:
            return struct.unpack("<HH", data[6:10])
        if fmt == "BMP" and len(data) >= 26:
            w, h = struct.unpack("<ii", data[18:26])
            return abs(w), abs(h)
        if fmt == "WebP" and len(data) >= 30 and data[12:16] == b"VP8X":
            return 1 + int.from_bytes(data[24:27], "little"), 1 + int.from_bytes(data[27:30], "little")
        if fmt == "JPEG":
            i = 2
            while i + 9 < len(data):
                if data[i] != 0xFF:
                    i += 1
                    continue
                marker = data[i + 1]
                if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:
                    i += 2
                    continue
                seg_len = struct.unpack(">H", data[i + 2:i + 4])[0]
                if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
                    h, w = struct.unpack(">HH", data[i + 5:i + 9])
                    return int(w), int(h)
                if seg_len < 2:
                    return 0, 0
                i += 2 + seg_len
    except Exception:  # nosec B110
        pass
    return 0, 0


def _xml_text(value: str) -> str:


    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _sidecar_xml(
    extent: dict | None, crs_wkt: str, width: int, height: int, img_format: str | None
) -> str:



    metadata_xml = (
        "  <Metadata>\n"
        '    <MDI key="AI_GENERATED">TRUE</MDI>\n'
        f'    <MDI key="AI_EDIT_DISCLAIMER">{_xml_text(AI_DISCLAIMER_TEXT)}</MDI>\n'
        "  </Metadata>\n"
    )
    geo_xml = ""
    if width <= 0 or height <= 0:


        log_warning(
            "plain-image rescue saved without georeferencing "
            f"(dimensions unknown for {img_format})"
        )
    elif extent is None:
        log_warning("plain-image rescue saved without georeferencing (extent unusable)")
    else:
        x_res = (extent["xmax"] - extent["xmin"]) / width
        y_res = (extent["ymax"] - extent["ymin"]) / height
        gt = ", ".join(
            f"{v:.16e}" for v in (extent["xmin"], x_res, 0.0, extent["ymax"], 0.0, -y_res)
        )
        srs_xml = f"  <SRS>{_xml_text(crs_wkt)}</SRS>\n" if crs_wkt else ""
        geo_xml = f"{srs_xml}  <GeoTransform>{gt}</GeoTransform>\n"
    return f"<PAMDataset>\n{metadata_xml}{geo_xml}</PAMDataset>\n"


def rescue_plain_image(
    image_data: bytes, extent: dict | None, crs_wkt: str, file_base: str
) -> str | None:









    img_format = detect_image_format(image_data)
    ext = _FALLBACK_EXT.get(img_format or "")
    if ext is None:
        return None
    width, height = read_image_dimensions(image_data, img_format)
    path = None
    try:

        path = _unique_output_path(ascii_safe_dir(fallback_output_dir()), file_base, ext)
        with open(path, "wb") as f:
            f.write(image_data)
        sidecar_xml = _sidecar_xml(extent, crs_wkt, width, height, img_format)
        with open(path + ".aux.xml", "w", encoding="utf-8") as f:
            f.write(sidecar_xml)
        return path
    except Exception as e:  # noqa: BLE001
        log_warning(f"plain-image rescue failed: {e}")

        if path and os.path.isfile(path) and os.path.getsize(path) == len(image_data):
            remove_with_retry(path + ".aux.xml")
            return path
        if path:
            remove_with_retry(path)
        return None
