




from __future__ import annotations

import math
import os
import struct
import tempfile
import time
import uuid

from osgeo import gdal, ogr, osr

from .i18n import tr
from .logger import log_debug, log_warning
from .output_paths import (  # noqa: F401
    OUTPUT_DIR_SETTING,
    ascii_safe_dir,
    fallback_output_dir,
    get_output_dir,
    remove_with_retry,
    replace_staged_file,
    set_output_dir,
)
from .output_paths import documents_default_dir as _documents_default_dir  # noqa: F401
from .output_paths import unique_output_path as _unique_output_path
from .slug import slugify as _slugify





_GTIFF_CREATION_OPTIONS = [
    "COMPRESS=DEFLATE",
    "PREDICTOR=2",
    "TILED=YES",
    "BLOCKXSIZE=256",
    "BLOCKYSIZE=256",


    "NUM_THREADS=ALL_CPUS",


    "BIGTIFF=IF_SAFER",
]



_GDAL_SAFE_FORMATS = {"PNG", "JPEG", "TIFF", "GIF", "BMP"}






_AI_DISCLAIMER_TEXT = "Synthetic imagery generated by AI. Not survey data or ground truth."






_FOREIGN_PROJ_MARKERS = ("rasterio", "pyproj", ".qgis_ai_segmentation", "venv")


def _restore_qgis_proj_paths(force: bool = False) -> None:




    try:
        values = [os.environ.get(var, "") for var in ("PROJ_LIB", "PROJ_DATA")]
        hijacked = any(
            marker in value.lower() for value in values for marker in _FOREIGN_PROJ_MARKERS
        )
        if not hijacked and not force:
            return
        from qgis.core import QgsProjUtils

        paths = [p for p in QgsProjUtils.searchPaths() if p and os.path.isdir(p)]
        if paths and hasattr(osr, "SetPROJSearchPaths"):
            osr.SetPROJSearchPaths(paths)
            log_warning(
                "PROJ search paths restored to QGIS defaults "
                f"(foreign override detected: {[v[:80] for v in values if v]})"
            )
    except Exception as err:  # nosec B110
        log_warning(f"PROJ path restore skipped: {err}")


def _safe_projection_wkt(crs_wkt: str) -> str | None:





    if not crs_wkt:
        return None
    err = ""
    for attempt in (1, 2):
        try:
            srs = osr.SpatialReference()
            if srs.ImportFromWkt(crs_wkt) == 0:
                return srs.ExportToWkt()
            err = gdal.GetLastErrorMsg() or "import returned an error code"
        except RuntimeError as e:
            err = str(e)
        if attempt == 1:
            log_warning(f"CRS import failed ({err}); restoring PROJ paths and retrying")
            _restore_qgis_proj_paths(force=True)
    log_warning(f"CRS import still failing after PROJ restore ({err})")
    return None


def _detect_image_format(data: bytes) -> str | None:

    if len(data) < 12:
        return None
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return "PNG"
    if data[:3] == b"\xff\xd8\xff":
        return "JPEG"
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "WebP"
    if data[:6] in (b"GIF87a", b"GIF89a"):
        return "GIF"
    if data[:4] in (b"II\x2a\x00", b"MM\x00\x2a", b"II\x2b\x00", b"MM\x00\x2b"):
        return "TIFF"
    if data[:2] == b"BM":
        return "BMP"

    if len(data) >= 12 and data[4:8] == b"ftyp":
        brand = data[8:12]
        if brand in (b"avif", b"avis"):
            return "AVIF"
        if brand in (b"heic", b"heix", b"mif1", b"msf1"):
            return "HEIF"
    return None


def memory_vector_driver():



    driver = ogr.GetDriverByName("MEM")
    if driver is not None and driver.GetMetadataItem("DCAP_VECTOR") == "YES":
        return driver
    return ogr.GetDriverByName("Memory")


def _create_gtiff(driver, path: str, w: int, h: int, bands: int):



    try:
        ds = driver.Create(path, w, h, bands, gdal.GDT_Byte, options=_GTIFF_CREATION_OPTIONS)
    except RuntimeError as e:
        return None, str(e)
    if ds is None:
        return None, gdal.GetLastErrorMsg() or "driver returned no dataset"
    return ds, ""


def _rasterize_crop_alpha(
    dst_ds, alpha_band_index: int, polygon_wkt: str, geotransform: tuple, projection_wkt: str | None,
    preserve_alpha: bool = True,
) -> None:









    w = dst_ds.RasterXSize
    h = dst_ds.RasterYSize
    mask_ds = gdal.GetDriverByName("MEM").Create("", w, h, 1, gdal.GDT_Byte)
    mask_ds.SetGeoTransform(geotransform)

    srs = None
    if projection_wkt:
        candidate = osr.SpatialReference()
        if candidate.ImportFromWkt(projection_wkt) == 0:
            srs = candidate
            mask_ds.SetProjection(projection_wkt)

    ogr_ds = memory_vector_driver().CreateDataSource("crop_mask")
    ogr_layer = ogr_ds.CreateLayer("zone", srs, ogr.wkbPolygon)
    geom = ogr.CreateGeometryFromWkt(polygon_wkt)
    if geom is None:
        raise RuntimeError("crop polygon WKT failed to parse")
    feature = ogr.Feature(ogr_layer.GetLayerDefn())
    feature.SetGeometry(geom)
    _check_gdal(ogr_layer.CreateFeature(feature), "crop feature")

    mask_band = mask_ds.GetRasterBand(1)
    _check_gdal(gdal.RasterizeLayer(mask_ds, [1], ogr_layer, burn_values=[255]), "crop rasterization")
    raw = mask_band.ReadRaster(0, 0, w, h, w, h, gdal.GDT_Byte)

    alpha_band = dst_ds.GetRasterBand(alpha_band_index)
    if raw is None or len(raw) != w * h:
        raise RuntimeError("Could not read crop mask")
    if preserve_alpha:
        existing = alpha_band.ReadRaster(0, 0, w, h, w, h, gdal.GDT_Byte)
        if existing is None or len(existing) != w * h:
            raise RuntimeError("Could not read complete alpha band")
        raw = bytes(value if mask else 0 for value, mask in zip(existing, raw))
    _check_gdal(alpha_band.WriteRaster(0, 0, w, h, raw, w, h, gdal.GDT_Byte), "crop alpha")
    alpha_band.SetColorInterpretation(gdal.GCI_AlphaBand)

    del mask_ds
    del ogr_ds


def _write_opaque_alpha_band(dst_ds, alpha_band_index: int) -> None:



    alpha_band = dst_ds.GetRasterBand(alpha_band_index)
    _check_gdal(alpha_band.Fill(255), "fill alpha")
    alpha_band.SetColorInterpretation(gdal.GCI_AlphaBand)


def read_crop_polygon_wkt(geotiff_path: str) -> str | None:






    try:
        ds = gdal.Open(geotiff_path)
        if ds is None:
            return None
        return ds.GetMetadataItem("AI_EDIT_CROP_POLYGON_WKT") or None
    except Exception:  # nosec B110
        return None


_FALLBACK_EXT = {
    "PNG": "png",
    "JPEG": "jpg",
    "GIF": "gif",
    "BMP": "bmp",
    "TIFF": "tif",
    "WebP": "webp",
    "AVIF": "avif",
    "HEIF": "heif",
}


def _image_dimensions(data: bytes, fmt: str | None) -> tuple[int, int]:


    try:
        if fmt == "PNG" and len(data) >= 24 and data[12:16] == b"IHDR":
            w, h = struct.unpack(">II", data[16:24])
            return int(w), int(h)
        if fmt == "GIF" and len(data) >= 10:
            return struct.unpack("<HH", data[6:10])
        if fmt == "BMP" and len(data) >= 26:
            w, h = struct.unpack("<ii", data[18:26])
            return abs(w), abs(h)
        if fmt == "WebP" and len(data) >= 30 and data[12:16] == b"VP8X":
            return 1 + int.from_bytes(data[24:27], "little"), 1 + int.from_bytes(data[27:30], "little")
        if fmt == "JPEG":
            i = 2
            while i + 9 < len(data):
                if data[i] != 0xFF:
                    i += 1
                    continue
                marker = data[i + 1]
                if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:
                    i += 2
                    continue
                seg_len = struct.unpack(">H", data[i + 2:i + 4])[0]
                if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
                    h, w = struct.unpack(">HH", data[i + 5:i + 9])
                    return int(w), int(h)
                if seg_len < 2:
                    return 0, 0
                i += 2 + seg_len
    except Exception:  # nosec B110
        pass
    return 0, 0


def _output_file_base(prompt: str) -> str:
    slug = (_slugify(prompt)[:40] if prompt else "") or "ai_edit"
    return f"{slug}_{time.strftime('%Y%m%d_%H%M%S')}"


def _rescue_plain_image(
    image_data: bytes,
    img_format: str | None,
    extent_dict: dict,
    crs_wkt: str,
    file_base: str,
    width: int,
    height: int,
) -> str | None:













    ext = _FALLBACK_EXT.get(img_format or "")
    if ext is None:
        return None
    path = None
    try:

        rescue_dir = fallback_output_dir()
        path = _unique_output_path(ascii_safe_dir(rescue_dir), file_base, ext)
        with open(path, "wb") as f:
            f.write(image_data)



        disclaimer_xml = _AI_DISCLAIMER_TEXT.replace("&", "&amp;")
        metadata_xml = (
            "  <Metadata>\n"
            '    <MDI key="AI_GENERATED">TRUE</MDI>\n'
            f'    <MDI key="AI_EDIT_DISCLAIMER">{disclaimer_xml}</MDI>\n'
            "  </Metadata>\n"
        )
        if width <= 0 or height <= 0:




            log_warning(
                "plain-image rescue saved without georeferencing "
                f"(dimensions unknown for {img_format})"
            )
            with open(path + ".aux.xml", "w", encoding="utf-8") as f:
                f.write(f"<PAMDataset>\n{metadata_xml}</PAMDataset>\n")
            return path
        extent_dict = _valid_extent(extent_dict, ("xmin", "ymin", "xmax", "ymax"))
        if extent_dict is None:
            log_warning("plain-image rescue saved without invalid georeferencing")
            return path
        x_res = (extent_dict["xmax"] - extent_dict["xmin"]) / width
        y_res = (extent_dict["ymax"] - extent_dict["ymin"]) / height
        gt = ", ".join(
            f"{v:.16e}"
            for v in (extent_dict["xmin"], x_res, 0.0, extent_dict["ymax"], 0.0, -y_res)
        )


        wkt_xml = crs_wkt.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        srs_xml = f"  <SRS>{wkt_xml}</SRS>\n" if crs_wkt else ""
        with open(path + ".aux.xml", "w", encoding="utf-8") as f:
            f.write(
                f"<PAMDataset>\n{metadata_xml}{srs_xml}"
                f"  <GeoTransform>{gt}</GeoTransform>\n</PAMDataset>\n"
            )
        return path
    except Exception as e:  # noqa: BLE001
        log_warning(f"plain-image rescue failed: {e}")

        if path and os.path.isfile(path) and os.path.getsize(path) == len(image_data):
            remove_with_retry(path + ".aux.xml")
            return path
        if path:
            remove_with_retry(path)
        return None





BEFORE_PATH_PROPERTY = "ai_edit/before_path"


def before_file_base(result_path: str) -> str:

    return os.path.splitext(os.path.basename(result_path))[0] + "_before"


def write_geotiff(
    image_data: bytes,
    extent_dict: dict,
    crs_wkt: str,
    output_dir: str,
    prompt: str = "",
    ctx=None,
    file_base: str | None = None,
) -> str:





    try:
        return _write_geotiff_gdal(
            image_data, extent_dict, crs_wkt, output_dir, prompt=prompt, ctx=ctx,
            file_base=file_base,
        )
    except Exception as gtiff_err:
        img_format = _detect_image_format(image_data)
        width, height = _image_dimensions(image_data, img_format)
        rescued = _rescue_plain_image(
            image_data, img_format, extent_dict, crs_wkt,
            file_base or _output_file_base(prompt), width, height,
        )
        if rescued is None:
            raise
        log_warning(f"GeoTIFF write failed ({gtiff_err}); rescued plain image to {rescued}")
        try:
            from . import telemetry
            from . import telemetry_events as te
            from .log_scrub import scrub_user_paths

            scrubbed = scrub_user_paths(str(gtiff_err))
            telemetry.track(te.PLUGIN_ERROR, {
                "stage": "write",
                "error_code": "write_geotiff_rescued",
                "error_message": scrubbed[:200],
            })
        except Exception:  # nosec B110
            pass
        if ctx is not None:
            ctx.output_path = rescued
            ctx.output_rescued = True
        return rescued


def _write_geotiff_gdal(
    image_data: bytes,
    extent_dict: dict,
    crs_wkt: str,
    output_dir: str,
    prompt: str = "",
    ctx=None,
    file_base: str | None = None,
) -> str:

    _restore_qgis_proj_paths()
    file_base = file_base or _output_file_base(prompt)



    try:
        os.makedirs(output_dir, exist_ok=True)
        resolved_dir = output_dir
    except OSError as e:
        log_warning(f"output_dir not writable ({e}); using fallback folder")
        resolved_dir = fallback_output_dir()




    resolved_dir = ascii_safe_dir(resolved_dir)

    xmin = extent_dict["xmin"]
    ymin = extent_dict["ymin"]
    xmax = extent_dict["xmax"]
    ymax = extent_dict["ymax"]
    if not all(math.isfinite(v) for v in (xmin, ymin, xmax, ymax)) or xmax <= xmin or ymax <= ymin:
        raise ValueError("Invalid raster extent")

    if not image_data:
        raise RuntimeError(tr("Server returned an empty response (0 bytes)"))

    img_format = _detect_image_format(image_data)
    head_hex = bytes(image_data[:16]).hex()
    log_debug(
        f"GeoTIFF input: {len(image_data)} bytes, "
        f"format={img_format or 'unknown'}, head={head_hex}"
    )
    if img_format is None:
        log_warning(
            f"Unrecognized image payload ({len(image_data)} bytes, head={head_hex})"
        )
        raise RuntimeError(tr(
            "Server returned data that is not a recognized image format. "
            "This usually means the server replied with an error page. "
            "Please try again or check the QGIS log."
        ))




    vsimem_path = f"/vsimem/ai_edit_{uuid.uuid4().hex}.img"


    primary_path = _unique_output_path(resolved_dir, file_base)
    output_path = primary_path
    src_ds = dst_ds = None
    try:
        gdal.FileFromMemBuffer(vsimem_path, bytes(image_data))
        try:
            src_ds = gdal.Open(vsimem_path)
        except RuntimeError as e:
            if img_format not in _GDAL_SAFE_FORMATS:
                raise RuntimeError(tr(
                    "Image format {fmt} is not supported by your QGIS "
                    "GDAL build. Please update QGIS or contact support."
                ).format(fmt=img_format)) from e
            raise
        if src_ds is None:
            if img_format not in _GDAL_SAFE_FORMATS:
                raise RuntimeError(tr(
                    "Image format {fmt} is not supported by your QGIS "
                    "GDAL build. Please update QGIS or contact support."
                ).format(fmt=img_format))
            raise RuntimeError(
                tr("Failed to open downloaded {fmt} image with GDAL").format(fmt=img_format)
            )







        if src_ds.RasterCount == 1 and src_ds.GetRasterBand(1).GetColorTable() is not None:
            log_debug("GeoTIFF: expanding palette image to RGB")
            color_table = src_ds.GetRasterBand(1).GetColorTable()
            has_alpha = any(color_table.GetColorEntry(i)[3] < 255 for i in range(color_table.GetCount()))
            expanded = gdal.Translate("", src_ds, format="MEM", rgbExpand="rgba" if has_alpha else "rgb")
            if expanded is not None:
                src_ds = expanded
            else:
                raise RuntimeError("Palette image expansion failed")

        recv_w = src_ds.RasterXSize
        recv_h = src_ds.RasterYSize
        src_bands = src_ds.RasterCount
        if recv_w <= 0 or recv_h <= 0 or src_bands <= 0:
            raise RuntimeError("Image has no usable pixels")
        alpha_source = next((i for i in range(1, src_bands + 1)
                             if src_ds.GetRasterBand(i).GetColorInterpretation() == gdal.GCI_AlphaBand), None)
        color_sources = [i for i in range(1, min(src_bands, 4) + 1) if i != alpha_source][:3]
        bands = len(color_sources)






        crop_polygon_wkt = getattr(ctx, "zone_polygon_wkt", None) if ctx is not None else None
        dst_bands = bands + 1 if crop_polygon_wkt or alpha_source else bands
        log_debug(f"GeoTIFF: received {recv_w}x{recv_h}px, {bands} bands")

        ext_width = xmax - xmin
        ext_height = ymax - ymin
        log_debug(f"GeoTIFF extent: {ext_width:.2f}x{ext_height:.2f} map units")

        if ctx is not None:
            ctx.received_image_width = recv_w
            ctx.received_image_height = recv_h
            ctx.received_size_bytes = len(image_data)
            ctx.crop_offsets = (0, 0, recv_w, recv_h)

        driver = gdal.GetDriverByName("GTiff")
        dst_ds, create_err = _create_gtiff(driver, output_path, recv_w, recv_h, dst_bands)
        if dst_ds is None:


            log_warning(
                f"GDAL Create failed at {primary_path} ({create_err}); retrying in fallback folder"
            )
            remove_with_retry(primary_path)
            fallback_dir = fallback_output_dir()
            if os.path.normcase(os.path.abspath(fallback_dir)) == os.path.normcase(
                os.path.abspath(output_dir)
            ):
                fallback_dir = tempfile.mkdtemp(prefix="terralab_ai_edit_")
            output_path = _unique_output_path(ascii_safe_dir(fallback_dir), file_base)
            dst_ds, create_err = _create_gtiff(driver, output_path, recv_w, recv_h, dst_bands)
        if dst_ds is None:
            remove_with_retry(output_path)
            msg = tr("Failed to create GeoTIFF at {path}").format(path=output_path)
            raise RuntimeError(f"{msg} ({create_err})")

        x_res = ext_width / recv_w
        y_res = ext_height / recv_h
        geotransform = (xmin, x_res, 0, ymax, 0, -y_res)
        _check_gdal(dst_ds.SetGeoTransform(geotransform), "geotransform")

        if ctx is not None:
            ctx.output_path = output_path
            ctx.geotransform = geotransform
            ctx.output_bands = dst_bands
            ctx.output_dimensions = (recv_w, recv_h)

        projection_wkt = _safe_projection_wkt(crs_wkt)
        if projection_wkt:
            _check_gdal(dst_ds.SetProjection(projection_wkt), "projection")
        else:


            log_warning("CRS embedding failed; writing GeoTIFF without projection")

        timestamp_iso = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        dst_ds.SetMetadataItem("AI_EDIT_PROMPT", prompt)
        dst_ds.SetMetadataItem("AI_EDIT_TIMESTAMP", timestamp_iso)
        dst_ds.SetMetadataItem("AI_EDIT_CRS", crs_wkt[:200])
        dst_ds.SetMetadataItem(
            "AI_EDIT_EXTENT",
            f"{xmin:.6f},{ymin:.6f},{xmax:.6f},{ymax:.6f}",
        )
        dst_ds.SetMetadataItem(
            "AI_EDIT_RESOLUTION",
            (getattr(ctx, "submitted_resolution", None) or "unknown") if ctx else "unknown",
        )
        dst_ds.SetMetadataItem(
            "AI_EDIT_MODEL",
            (getattr(ctx, "model_name", None) or "AI Edit") if ctx else "AI Edit",
        )


        if ctx is not None:
            for tag, value in (
                ("AI_EDIT_REQUEST_ID", getattr(ctx, "request_id", None)),
                ("AI_EDIT_PARENT_REQUEST_ID", getattr(ctx, "parent_request_id", None)),
                ("AI_EDIT_TEMPLATE_ID", getattr(ctx, "template_id", None)),
                ("AI_EDIT_TEMPLATE_NAME", getattr(ctx, "template_name", None)),
                ("AI_EDIT_ASPECT_RATIO", getattr(ctx, "submitted_aspect_ratio", None)),
                ("AI_EDIT_GROUND_RESOLUTION_M", getattr(ctx, "ground_resolution_m", None)),
            ):
                if value is not None:
                    dst_ds.SetMetadataItem(tag, str(value))

        dst_ds.SetMetadataItem("TIFFTAG_SOFTWARE", "AI Edit by TerraLab")
        dst_ds.SetMetadataItem(
            "TIFFTAG_DATETIME", time.strftime("%Y:%m:%d %H:%M:%S", time.gmtime())
        )
        dst_ds.SetMetadataItem("TIFFTAG_IMAGEDESCRIPTION", prompt[:512])


        dst_ds.SetMetadataItem("AI_GENERATED", "TRUE")
        dst_ds.SetMetadataItem("AI_EDIT_DISCLAIMER", _AI_DISCLAIMER_TEXT)
        if crop_polygon_wkt:
            dst_ds.SetMetadataItem("AI_EDIT_CROP", "POLYGON")
            dst_ds.SetMetadataItem("AI_EDIT_CROP_POLYGON_WKT", crop_polygon_wkt)






        for i, source_index in enumerate(color_sources, 1):
            source_band = src_ds.GetRasterBand(source_index)
            target_band = dst_ds.GetRasterBand(i)
            _copy_band(source_band, target_band, recv_w, recv_h)
            _check_gdal(
                target_band.SetColorInterpretation(source_band.GetColorInterpretation()), "color interpretation"
            )
        if alpha_source:
            _copy_band(src_ds.GetRasterBand(alpha_source), dst_ds.GetRasterBand(bands + 1), recv_w, recv_h)
            _check_gdal(
                dst_ds.GetRasterBand(bands + 1).SetColorInterpretation(gdal.GCI_AlphaBand), "alpha interpretation"
            )

        if crop_polygon_wkt:
            if not alpha_source:
                _write_opaque_alpha_band(dst_ds, bands + 1)



            try:
                _rasterize_crop_alpha(
                    dst_ds, bands + 1, crop_polygon_wkt, geotransform, projection_wkt,
                    preserve_alpha=bool(alpha_source),
                )
            except Exception as err:  # noqa: BLE001
                log_warning(f"crop alpha rasterization failed ({err}); using opaque band")
                if alpha_source:
                    _copy_band(src_ds.GetRasterBand(alpha_source), dst_ds.GetRasterBand(bands + 1), recv_w, recv_h)
                else:
                    _write_opaque_alpha_band(dst_ds, bands + 1)
                dst_ds.SetMetadataItem("AI_EDIT_CROP", None)
                dst_ds.SetMetadataItem("AI_EDIT_CROP_POLYGON_WKT", None)




        try:
            levels = []
            factor = 2
            while max(recv_w, recv_h) / factor >= 256:
                levels.append(factor)
                factor *= 2
            if levels:


                previous = gdal.GetThreadLocalConfigOption("COMPRESS_OVERVIEW", None)
                gdal.SetThreadLocalConfigOption("COMPRESS_OVERVIEW", "DEFLATE")
                try:
                    _check_gdal(dst_ds.BuildOverviews("AVERAGE", levels), "overviews")
                finally:
                    gdal.SetThreadLocalConfigOption("COMPRESS_OVERVIEW", previous)
        except Exception as err:  # noqa: BLE001
            log_warning(f"overview build skipped: {err}")

        _check_gdal(dst_ds.FlushCache(), "flush output")
        dst_ds = None
        src_ds = None
    except BaseException:


        dst_ds = None
        src_ds = None
        remove_with_retry(output_path)
        raise
    finally:
        try:
            gdal.Unlink(vsimem_path)
        except RuntimeError as err:
            log_warning(f"Image buffer cleanup failed: {err}")




    if not os.path.exists(output_path) or os.path.getsize(output_path) == 0:
        raise RuntimeError(
            tr("GeoTIFF write produced no file at {path}").format(path=output_path)
        )

    return output_path


def _check_gdal(result, operation):

    if result not in (0, None):
        raise RuntimeError(f"GDAL {operation} failed: {gdal.GetLastErrorMsg()}")


def _copy_band(source, target, width, height):

    for y in range(0, height, 256):
        rows = min(256, height - y)
        raw = source.ReadRaster(0, y, width, rows, width, rows, gdal.GDT_Byte)
        if raw is None or len(raw) != width * rows:
            raise RuntimeError("Incomplete raster band read")
        _check_gdal(target.WriteRaster(0, y, width, rows, raw, width, rows, gdal.GDT_Byte), "band write")


def _valid_extent(value, keys):
    if not isinstance(value, dict):
        return None
    try:
        coords = [float(value[key]) for key in keys]
    except (KeyError, TypeError, ValueError, OverflowError):
        return None
    if not all(math.isfinite(v) for v in coords) or coords[2] <= coords[0] or coords[3] <= coords[1]:
        return None
    return dict(zip(("xmin", "ymin", "xmax", "ymax"), coords))


def extent_and_crs_from_job(job: dict) -> tuple[dict, str] | None:









    from qgis.core import QgsCoordinateReferenceSystem

    authid_value = job.get("crs_authid")
    authid = authid_value.strip() if isinstance(authid_value, str) else ""
    bbox = job.get("bbox")
    native = _valid_extent(bbox, ("xmin", "ymin", "xmax", "ymax"))
    if authid and native:
        crs = QgsCoordinateReferenceSystem(authid)
        if crs.isValid():
            return native, crs.toWkt()

    wgs = job.get("bbox_wgs84")
    geographic = _valid_extent(wgs, ("west", "south", "east", "north"))
    if (geographic and -180 <= geographic["xmin"] < geographic["xmax"] <= 180
            and -90 <= geographic["ymin"] < geographic["ymax"] <= 90):
        crs = QgsCoordinateReferenceSystem("EPSG:4326")
        if crs.isValid():
            return geographic, crs.toWkt()

    return None
